version: '3.8'
services:
  fe-app:
    image: registry.cn-hangzhou.aliyuncs.com/once_fine/huskky:aaa
    depends_on:
      - nest-app
    ports:
      - 80:80
    networks:
      - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    # ports:
    #   - 3005:3005
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/sevan/wsf/nest/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/sevan/wsf/nest/redis-playground:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
